services:
  rc-server:
    build:
      context: ./rc-server
    container_name: rc-server
    environment:
      - SERVER_BIND_IP=0.0.0.0
      - SERVER_BIND_PORT=5700 # arbitrario

  rc-client-nodes:
    build:
      context: ./rc-client-nodes
    # container_name: rc-client-nodes
    environment:
      - TARGET_IP=rc-server
      - TARGET_PORT=5700 # arbitrario, mismo que server

